[provider]
cluster = "localnet"
wallet = "./keypairs/update-authority.json"

[programs.mainnet]
rewards_center = "EMw5PpPu7E92uBKYQbLWv6ioghSDehJr1PL7fDvhC6CK"

[programs.devnet]
rewards_center = "EMw5PpPu7E92uBKYQbLWv6ioghSDehJr1PL7fDvhC6CK"

[programs.testnet]
rewards_center = "EMw5PpPu7E92uBKYQbLWv6ioghSDehJr1PL7fDvhC6CK"

[programs.localnet]
rewards_center = "EMw5PpPu7E92uBKYQbLWv6ioghSDehJr1PL7fDvhC6CK"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-discount.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/stake-entry/stake-unstake-pnft.test.ts"

# [test]
# startup_wait = 10000